spring:
  datasource:
    url: jdbc:mysql://localhost:3306/magasin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver